In [2]:
import torch

torch.tensor([[2,1,4,3],[1,2,3,4],[4,3,2,1]])

tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])

In [ ]:
torch.randn(3,4)

tensor([[-1.6133, -0.4605,  0.6902, -0.5740],
        [-0.1019, -1.2362, -2.7134, -1.3084],
        [-0.0389,  1.2801,  0.3101,  1.4276]])

In [4]:
X=torch.tensor([1,2,4,8,10])
y=torch.tensor([1,2,3,4,10])
X/y

tensor([1.0000, 1.0000, 1.3333, 2.0000, 1.0000])

In [5]:
X=torch.arange(12,dtype=torch.float32).reshape((3,4))
y=torch.tensor([[2,1,4,3],[1,2,3,4],[4,3,2,1]])
torch.cat((X,y),dim=0)

torch.cat((X,y),dim=1)

tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
        [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
        [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]])

In [6]:
import torch
x = torch.tensor([[1,2,3], [4,5,6]])  # shape=(2, 3)，2行3列
print(x.sum(dim=0))  # 对dim=0求和 → 结果是[5,7,9]（把两行的对应列加起来）

tensor([5, 7, 9])


In [7]:
import os
os.makedirs(os.path.join('..', 'data'), exist_ok=True)
data_file = os.path.join('..', 'data', 'house_tiny.csv')
with open(data_file, 'w') as f:
    f.write('NumRooms,Alley,Price\n') # 列名
    f.write('NA,Pave,127500\n') # 每行表示一个数据样本
    f.write('2,NA,106000\n')
    f.write('4,NA,178100\n')
    f.write('NA,NA,140000\n')

In [8]:
import pandas as pd

data=pd.read_csv(data_file)
print(data)

   NumRooms Alley   Price
0       NaN  Pave  127500
1       2.0   NaN  106000
2       4.0   NaN  178100
3       NaN   NaN  140000


In [13]:
inputs,outputs=data.iloc[:,0:2],data.iloc[:,2]

inputs['NumRooms']=inputs['NumRooms'].fillna(data.loc[:,'NumRooms'].mean())

# inputs=pd.get_dummies(inputs,)
inputs

,NumRooms,Alley
0,3.0,Pave
1,2.0,NaN
2,4.0,NaN
3,3.0,NaN


In [ ]:
A=torch.arange(20,dtype=torch.float32).reshape(5,4)

B=A.clone()

id(A)==id(B)

False

In [17]:
torch.tensor(range(4))


tensor([0, 1, 2, 3])

In [19]:
u=torch.tensor([3.0,-4.0])
torch.norm(u)
torch.abs(u).sum()

tensor(7.)

In [ ]:
%matplotlib inline

import numpy as np
from matplotlib_inline import backend_inline

from d2l import torch as d2l

def f(x):
    return 3*x**2-4*x

def numerical_lim(f,x,h):
    return (f(x+h)-f(x))/h

h=0.1

for i in range(5):
    print(f'h={h:.5f}, numerical limit={numerical_lim(f,1,h):.5f}')
    h*0.1

h=0.10000, numerical limit=2.30000
h=0.01000, numerical limit=2.03000
h=0.00100, numerical limit=2.00300
h=0.00010, numerical limit=2.00030
h=0.00001, numerical limit=2.00003


In [3]:
def use_svg_display(): #@save
    backend_inline.set_matplotlib_formats('svg')#设置输出的格式

In [ ]:
def set_figsize(figsize=(3.5, 2.5)): #@save
    use_svg_display()
    d2l.plt.rcParams['figure.figsize'] = figsize

In [2]:
#@save

def set_axes(axes,xlabel,ylabel,xlim,ylim,xscale,yscale,legend):

    axes.set_xlabel(xlabel)
    axes.set_ylabel(ylabel)
    axes.set_xscale(xscale)
    axes.set_yscale(yscale)
    axes.set_xlim(xlim)
    axes.set_ylim(ylim)

    if legend:
        axes.legend(legend)
    axes.grid()

In [ ]:
#@save
def plot(X, Y=None, xlabel=None, ylabel=None, legend=None, xlim=None,ylim=None, xscale='linear', yscale='linear',fmts=('-', 'm--', 'g-.', 'r:'), figsize=(3.5, 2.5), axes=None):

    if legend is None:#图标列表
        legend = []
    set_figsize(figsize)
    axes = axes if axes else d2l.plt.gca()
    
    def has_one_axis(X):
        return (hasattr(X,'ndim') and X.ndim==1 or isinstance(X,list) and not hasattr(X[0],'__len__'))

    

    

Help on built-in function hasattr in module builtins:

hasattr(obj, name, /)
    Return whether the object has an attribute with the given name.
    
    This is done by calling getattr(obj, name) and catching AttributeError.



In [9]:
import torch

x=torch.arange(4.0)#一维张量
x

tensor([0., 1., 2., 3.])

In [ ]:
x.requires_grad_(True)

None


In [18]:
x=torch.arange(4.0,requires_grad=True)
y=2*torch.dot(x,x)
y

y.backward()
x.grad==4*x

tensor([True, True, True, True])

In [ ]:
x.grad_zeros_()# 把对应的梯度原地清零