In [2]:
import math
import numpy as np
import torch 
from torch import nn
from d2l import torch as d2l

In [3]:
max_degree=20

n_train,n_test=100,100 

true_w=np.zeros(max_degree)
true_w[0:4]=np.array([5,1.2,-3.4,5.6])

features=np.random.normal(size=(n_train+n_test,1))
np.random.shuffle(features)
poly_features=np.power(features,np.arange(max_degree).reshape(1,-1))

for i in range(max_degree):
    poly_features[:,i]/=math.gamma(i+1)#gamma(n)=(n-1)!

labels=np.dot(poly_features,true_w)
labels+=np.random.normal(scale=0.1,size=labels.shape)

In [5]:
true_w,features,poly_features,labels=[torch.tensor(x,dtype=torch.float32)for x in [true_w,features,poly_features,labels]]

In [7]:
features[:2],poly_features[:2,:],labels[:2]

(tensor([[ 0.3812],
         [-0.2488]]),
 tensor([[ 1.0000e+00,  3.8118e-01,  7.2648e-02,  9.2306e-03,  8.7963e-04,
           6.7059e-05,  4.2602e-06,  2.3199e-07,  1.1053e-08,  4.6815e-10,
           1.7845e-11,  6.1837e-13,  1.9642e-14,  5.7594e-16,  1.5681e-17,
           3.9849e-19,  9.4934e-21,  2.1286e-22,  4.5077e-24,  9.0433e-26],
         [ 1.0000e+00, -2.4877e-01,  3.0942e-02, -2.5658e-03,  1.5957e-04,
          -7.9392e-06,  3.2917e-07, -1.1698e-08,  3.6376e-10, -1.0055e-11,
           2.5012e-13, -5.6566e-15,  1.1726e-16, -2.2439e-18,  3.9873e-20,
          -6.6126e-22,  1.0281e-23, -1.5045e-25,  2.0793e-27, -2.7224e-29]]),
 tensor([5.2946, 4.5927]))